// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdmiwtdqabaoyeexqvgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbWl3dGRxYWJhb3llZXhxdmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODQ3NjYsImV4cCI6MjA2MDM2MDc2Nn0.uyzpp6JmhBpmVAIIJSac3lJv-P8-y4T5BBHJl0ngymM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper for GoHighLevel API - use correct API format
export const getGhlApiHeaders = (apiKey: string) => {
  // Check if it's a JWT (contains dots with base64 segments)
  if (apiKey && apiKey.split('.').length === 3) {
    return {
      'Authorization': `Bearer ${apiKey}`,
      'Version': '2021-07-28',
      'Accept': 'application/json',
    };
  } 
  // Otherwise treat as a standard API key
  else if (apiKey) {
    return {
      'Authorization': apiKey,
      'Version': '2021-07-28',
      'Accept': 'application/json',
    };
  }
  
  return {
    'Accept': 'application/json',
  };
};
